### ISSUE TITLE
Snapshot matching syntax

### ISSUE THREAD

**Issue by Bobronium** [b0g3r/perseus#5]
Is it just me, or the first one reads more natural than the second one?
```py
assert snapshot.match('value')
```

```py
snapshot.assert_match('value)
```

Second one reminds me of `unittests`'s assert methods 😢 

Another option is `assert snapshot == value`, but it breaks common `actual == expected` pattern, so I'm not sure whether it should be used.

**Comment by b0g3r** [comment]
Thank you for the great idea! I totally agree with you, syntax with assert looks more natural. I actually didn't like `pytest-mock` because of `mocked.assert_called_once()` 😅
